<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Collection.fs" />
    <Compile Include="Result.fs" />
    <Compile Include="Math.fs" />
    <Compile Include="Text.fs" />
    <Compile Include="Io.fs" />
    <Compile Include="Nbt.fs" />
  </ItemGroup>
</Project>